import { EnemyDefinition, EnemyType } from '../types';

export const ENEMY_DEFINITIONS: Record<EnemyType, EnemyDefinition> = {
  goblin: {
    type: 'goblin',
    name: 'Goblin',
    hp: 60,
    speed: 2.5,
    reward: 10,
    emoji: '👺',
    color: '#8BC34A',
    size: 24,
  },
  orc: {
    type: 'orc',
    name: 'Orco',
    hp: 150,
    speed: 1.5,
    reward: 20,
    emoji: '👹',
    color: '#4CAF50',
    size: 30,
  },
  troll: {
    type: 'troll',
    name: 'Trol',
    hp: 300,
    speed: 1,
    reward: 35,
    emoji: '🧌',
    color: '#795548',
    size: 36,
  },
  dragon: {
    type: 'dragon',
    name: 'Dragón',
    hp: 500,
    speed: 2,
    reward: 60,
    emoji: '🐉',
    color: '#F44336',
    size: 40,
  },
  boss: {
    type: 'boss',
    name: '¡JEFE!',
    hp: 1500,
    speed: 0.8,
    reward: 200,
    emoji: '💀',
    color: '#212121',
    size: 50,
  },
};
