import { LevelDefinition } from '../types';

export const LEVELS: LevelDefinition[] = [
  // ── EASY ──────────────────────────────────────────────────────────────────
  {
    id: 'easy_1',
    name: 'Pradera Verde',
    difficulty: 'easy',
    description: 'Un camino recto. Perfecto para comenzar.',
    emoji: '🌿',
    gridCols: 10,
    gridRows: 8,
    startingCoins: 200,
    lives: 20,
    unlocked: true,
    path: [
      { x: 0, y: 3 }, { x: 1, y: 3 }, { x: 2, y: 3 }, { x: 3, y: 3 },
      { x: 4, y: 3 }, { x: 5, y: 3 }, { x: 6, y: 3 }, { x: 7, y: 3 },
      { x: 8, y: 3 }, { x: 9, y: 3 },
    ],
    waves: [
      { delayBefore: 2000, enemies: [{ type: 'goblin', count: 5, interval: 1000 }] },
      { delayBefore: 3000, enemies: [{ type: 'goblin', count: 8, interval: 800 }] },
      { delayBefore: 4000, enemies: [{ type: 'goblin', count: 5, interval: 800 }, { type: 'orc', count: 2, interval: 1500 }] },
    ],
  },
  {
    id: 'easy_2',
    name: 'Río Tranquilo',
    difficulty: 'easy',
    description: 'Una curva suave a lo largo del río.',
    emoji: '🏞️',
    gridCols: 10,
    gridRows: 8,
    startingCoins: 180,
    lives: 20,
    unlocked: true,
    path: [
      { x: 0, y: 1 }, { x: 1, y: 1 }, { x: 2, y: 1 }, { x: 3, y: 1 },
      { x: 3, y: 2 }, { x: 3, y: 3 }, { x: 3, y: 4 },
      { x: 4, y: 4 }, { x: 5, y: 4 }, { x: 6, y: 4 },
      { x: 6, y: 5 }, { x: 6, y: 6 },
      { x: 7, y: 6 }, { x: 8, y: 6 }, { x: 9, y: 6 },
    ],
    waves: [
      { delayBefore: 2000, enemies: [{ type: 'goblin', count: 6, interval: 900 }] },
      { delayBefore: 3000, enemies: [{ type: 'goblin', count: 8, interval: 700 }, { type: 'orc', count: 3, interval: 1200 }] },
      { delayBefore: 4000, enemies: [{ type: 'orc', count: 6, interval: 1000 }] },
    ],
  },

  // ── MEDIUM ────────────────────────────────────────────────────────────────
  {
    id: 'medium_1',
    name: 'Bosque Oscuro',
    difficulty: 'medium',
    description: 'Múltiples curvas entre los árboles.',
    emoji: '🌲',
    gridCols: 10,
    gridRows: 9,
    startingCoins: 250,
    lives: 15,
    unlocked: true,
    path: [
      { x: 0, y: 2 }, { x: 1, y: 2 }, { x: 2, y: 2 },
      { x: 2, y: 3 }, { x: 2, y: 4 }, { x: 2, y: 5 },
      { x: 3, y: 5 }, { x: 4, y: 5 }, { x: 5, y: 5 },
      { x: 5, y: 4 }, { x: 5, y: 3 }, { x: 5, y: 2 },
      { x: 6, y: 2 }, { x: 7, y: 2 },
      { x: 7, y: 3 }, { x: 7, y: 4 }, { x: 7, y: 5 }, { x: 7, y: 6 },
      { x: 8, y: 6 }, { x: 9, y: 6 },
    ],
    waves: [
      { delayBefore: 2000, enemies: [{ type: 'goblin', count: 8, interval: 700 }] },
      { delayBefore: 3000, enemies: [{ type: 'orc', count: 6, interval: 1000 }] },
      { delayBefore: 3000, enemies: [{ type: 'goblin', count: 6, interval: 600 }, { type: 'orc', count: 4, interval: 900 }] },
      { delayBefore: 4000, enemies: [{ type: 'troll', count: 3, interval: 2000 }] },
    ],
  },
  {
    id: 'medium_2',
    name: 'Ruinas Antiguas',
    difficulty: 'medium',
    description: 'Laberinto de ruinas con trampas.',
    emoji: '🏛️',
    gridCols: 10,
    gridRows: 9,
    startingCoins: 220,
    lives: 15,
    unlocked: false,
    path: [
      { x: 0, y: 0 }, { x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 },
      { x: 3, y: 1 }, { x: 3, y: 2 }, { x: 3, y: 3 }, { x: 3, y: 4 },
      { x: 4, y: 4 }, { x: 5, y: 4 }, { x: 6, y: 4 }, { x: 6, y: 3 },
      { x: 6, y: 2 }, { x: 6, y: 1 }, { x: 7, y: 1 }, { x: 8, y: 1 },
      { x: 8, y: 2 }, { x: 8, y: 3 }, { x: 8, y: 4 }, { x: 8, y: 5 },
      { x: 8, y: 6 }, { x: 9, y: 6 },
    ],
    waves: [
      { delayBefore: 2000, enemies: [{ type: 'goblin', count: 10, interval: 600 }] },
      { delayBefore: 3000, enemies: [{ type: 'orc', count: 7, interval: 900 }] },
      { delayBefore: 3000, enemies: [{ type: 'troll', count: 4, interval: 1800 }] },
      { delayBefore: 4000, enemies: [{ type: 'orc', count: 5, interval: 800 }, { type: 'troll', count: 2, interval: 2000 }] },
    ],
  },

  // ── HARD ─────────────────────────────────────────────────────────────────
  {
    id: 'hard_1',
    name: 'Volcán Maldito',
    difficulty: 'hard',
    description: 'Camino retorcido con hordas de dragones.',
    emoji: '🌋',
    gridCols: 10,
    gridRows: 10,
    startingCoins: 300,
    lives: 10,
    unlocked: false,
    path: [
      { x: 0, y: 5 }, { x: 1, y: 5 }, { x: 1, y: 4 }, { x: 1, y: 3 },
      { x: 2, y: 3 }, { x: 3, y: 3 }, { x: 3, y: 4 }, { x: 3, y: 5 }, { x: 3, y: 6 },
      { x: 4, y: 6 }, { x: 5, y: 6 }, { x: 5, y: 5 }, { x: 5, y: 4 }, { x: 5, y: 3 }, { x: 5, y: 2 },
      { x: 6, y: 2 }, { x: 7, y: 2 }, { x: 7, y: 3 }, { x: 7, y: 4 }, { x: 7, y: 5 }, { x: 7, y: 6 }, { x: 7, y: 7 },
      { x: 8, y: 7 }, { x: 9, y: 7 },
    ],
    waves: [
      { delayBefore: 2000, enemies: [{ type: 'orc', count: 8, interval: 700 }] },
      { delayBefore: 3000, enemies: [{ type: 'troll', count: 5, interval: 1200 }] },
      { delayBefore: 3000, enemies: [{ type: 'dragon', count: 3, interval: 2000 }] },
      { delayBefore: 3000, enemies: [{ type: 'orc', count: 6, interval: 600 }, { type: 'dragon', count: 2, interval: 2500 }] },
      { delayBefore: 5000, enemies: [{ type: 'boss', count: 1, interval: 0 }] },
    ],
  },

  // ── EXTREME ──────────────────────────────────────────────────────────────
  {
    id: 'extreme_1',
    name: 'El Abismo Final',
    difficulty: 'extreme',
    description: 'Solo los más valientes sobreviven.',
    emoji: '💀',
    gridCols: 10,
    gridRows: 10,
    startingCoins: 350,
    lives: 5,
    unlocked: false,
    path: [
      { x: 0, y: 2 }, { x: 1, y: 2 }, { x: 1, y: 3 }, { x: 1, y: 4 }, { x: 1, y: 5 }, { x: 1, y: 6 }, { x: 1, y: 7 },
      { x: 2, y: 7 }, { x: 3, y: 7 }, { x: 3, y: 6 }, { x: 3, y: 5 }, { x: 3, y: 4 }, { x: 3, y: 3 }, { x: 3, y: 2 }, { x: 3, y: 1 },
      { x: 4, y: 1 }, { x: 5, y: 1 }, { x: 5, y: 2 }, { x: 5, y: 3 }, { x: 5, y: 4 }, { x: 5, y: 5 }, { x: 5, y: 6 }, { x: 5, y: 7 }, { x: 5, y: 8 },
      { x: 6, y: 8 }, { x: 7, y: 8 }, { x: 7, y: 7 }, { x: 7, y: 6 }, { x: 7, y: 5 }, { x: 7, y: 4 }, { x: 7, y: 3 }, { x: 7, y: 2 },
      { x: 8, y: 2 }, { x: 9, y: 2 },
    ],
    waves: [
      { delayBefore: 1500, enemies: [{ type: 'orc', count: 10, interval: 500 }] },
      { delayBefore: 2000, enemies: [{ type: 'troll', count: 8, interval: 800 }] },
      { delayBefore: 2000, enemies: [{ type: 'dragon', count: 5, interval: 1500 }] },
      { delayBefore: 2000, enemies: [{ type: 'troll', count: 6, interval: 700 }, { type: 'dragon', count: 3, interval: 2000 }] },
      { delayBefore: 2000, enemies: [{ type: 'dragon', count: 6, interval: 1200 }] },
      { delayBefore: 3000, enemies: [{ type: 'boss', count: 2, interval: 5000 }] },
    ],
  },
];
