import { TowerDefinition, TowerType } from '../types';

export const TOWER_DEFINITIONS: Record<TowerType, TowerDefinition> = {
  archer: {
    id: 'archer',
    name: 'Arquero',
    description: 'Veloz y preciso. Ideal para enemigos rápidos.',
    cost: 50,
    damage: 15,
    range: 3,
    fireRate: 2,
    emoji: '🏹',
    color: '#4CAF50',
    maxLevel: 3,
    upgradeCost: 40,
    unlocked: true,
  },
  cannon: {
    id: 'cannon',
    name: 'Cañón',
    description: 'Daño en área. Destruye grupos de enemigos.',
    cost: 100,
    damage: 40,
    range: 2.5,
    fireRate: 0.7,
    emoji: '💣',
    color: '#FF5722',
    maxLevel: 3,
    upgradeCost: 80,
    unlocked: true,
  },
  mage: {
    id: 'mage',
    name: 'Mago',
    description: 'Daño mágico que ignora armadura.',
    cost: 120,
    damage: 30,
    range: 3.5,
    fireRate: 1,
    emoji: '🔮',
    color: '#9C27B0',
    maxLevel: 3,
    upgradeCost: 100,
    unlocked: false,
  },
  ice: {
    id: 'ice',
    name: 'Torre de Hielo',
    description: 'Ralentiza enemigos al 50% de velocidad.',
    cost: 90,
    damage: 10,
    range: 2.5,
    fireRate: 1.2,
    emoji: '❄️',
    color: '#00BCD4',
    maxLevel: 3,
    upgradeCost: 70,
    unlocked: false,
  },
  lightning: {
    id: 'lightning',
    name: 'Rayo',
    description: 'Encadena daño entre enemigos cercanos.',
    cost: 150,
    damage: 50,
    range: 3,
    fireRate: 0.8,
    emoji: '⚡',
    color: '#FFC107',
    maxLevel: 3,
    upgradeCost: 120,
    unlocked: false,
  },
};

export const TOWER_UNLOCK_COST: Record<TowerType, number> = {
  archer: 0,
  cannon: 0,
  mage: 200,
  ice: 150,
  lightning: 300,
};
